---

- name: Update dotfiles
  hosts: "{{ target | default('all') }}"
  
  tasks:
    - name: Update dotfiles from repository
      include_role:
        name: repository
    
    - name: Configure Bash completion
      include_role:
        name: bash_completion
    
    - name: Configure Vim plugins
      import_role:
        name: vim_plugins
